export const LINK = "http://localhost:3000";

// faculties actions
export const LOAD_FACULTIES = "LOAD_FACULTIES";
export const lOAD_FACULTIES_SUCCESS = "lOAD_FACULTIES_SUCCESS";
export const lOAD_FACULTIES_ERROR = "lOAD_FACULTIES_ERROR";

// programs actions
export const LOAD_PROGRAMS = "LOAD_PROGRAMS";
export const lOAD_PROGRAMS_SUCCESS = "lOAD_PROGRAMS_SUCCESS";
export const lOAD_PROGRAMS_ERROR = "lOAD_PROGRAMS_ERROR";

// programs actions
export const LOAD_OUTCOMESTANDARDS = "LOAD_OUTCOMESTANDARDS";
export const LOAD_OUTCOMESTANDARDS_SUCCESS = "LOAD_OUTCOMESTANDARDS_SUCCESS";
export const LOAD_OUTCOMESTANDARDS_ERROR = "LOAD_OUTCOMESTANDARDS_ERROR";
