// faculties actions
export const LOAD_FACULTIES = "LOAD_FACULTIES";
export const LOAD_FACULTIES_SUCCESS = "LOAD_FACULTIES_SUCCESS";
export const LOAD_FACULTIES_ERROR = "LOAD_FACULTIES_ERROR";

// programs actions
export const LOAD_PROGRAMS = "LOAD_PROGRAMS";
export const LOAD_PROGRAMS_SUCCESS = "LOAD_PROGRAMS_SUCCESS";
export const LOAD_PROGRAMS_ERROR = "LOAD_PROGRAMS_ERROR";

// outcomeStandards actions
export const LOAD_OUTCOMESTANDARDS = "LOAD_OUTCOMESTANDARDS";
export const LOAD_OUTCOMESTANDARDS_SUCCESS = "LOAD_OUTCOMESTANDARDS_SUCCESS";
export const LOAD_OUTCOMESTANDARDS_ERROR = "LOAD_OUTCOMESTANDARDS_ERROR";

// detailOutcomeStandard actions
export const SAVE_DETAIL_OUTCOMESTANDARD = "SAVE_DETAIL_OUTCOMESTANDARD";
export const SAVE_DETAIL_OUTCOMESTANDARD_SUCCESS = "SAVE_DETAIL_OUTCOMESTANDARD_SUCCESS";
export const SAVE_DETAIL_OUTCOMESTANDARD_ERROR = "SAVE_DETAIL_OUTCOMESTANDARD_ERROR";
